### ISSUE TITLE
Layouts show overflowing elements

### ISSUE THREAD

**Issue by MTRNord** [gdiepen/latexbeamer-handoutWithNotes#13]
Hi, I have a document where an image is intentionally is places partially outside the presentation itself.

This works fine with beamer, however with this package the full image is being rendered. Is there a way to make it clip at the border like the beamer layout would do?

**Comment by MTRNord** [comment]
Example:
![image](https://user-images.githubusercontent.com/1374914/217083607-199a092a-9893-479d-8a01-67b68ccb9408.png)

**Comment by samcarter** [comment]
@MTRNord  Can you make a minimal reproducible example? This problem can usually be avoided by changing the settings of pgfpages.

**Comment by samcarter** [comment]
One could for example use rounded corners which aren't round....

```
\documentclass{beamer}

\usepackage{pgfpages}
\pgfpageslogicalpageoptions{1}{corner width=0pt}
\pgfpageslogicalpageoptions{2}{corner width=0pt}
\pgfpageslogicalpageoptions{3}{corner width=0pt}
\pgfpageslogicalpageoptions{4}{corner width=0pt}
\pgfpageslogicalpageoptions{5}{corner width=0pt}
\pgfpageslogicalpageoptions{6}{corner width=0pt}

\usepackage{handoutWithNotes}
\pgfpagesuselayout{3 on 1 with notes}

\begin{document}
	
\begin{frame}
	abc \includegraphics[scale=3]{example-image-duck}
\end{frame}	

\begin{frame}
	abc \includegraphics[scale=3]{example-image-duck}
\end{frame}	
	
\end{document}
```

![document2](https://user-images.githubusercontent.com/43832342/217247851-a51db3ef-1584-4191-b821-c361e836d8b5.png)

**Comment by MTRNord** [comment]
> @MTRNord Can you make a minimal reproducible example? This problem can usually be avoided by changing the settings of pgfpages.

I have some more meetings today after it I can do that :)

> One could for example use rounded corners which aren't round....

This seems to work for half of the frames in "2 on 1 with notes". The upper frame has it clipped properly, while the second frame is not. :thinking:

**Comment by samcarter** [comment]
@MTRNord  Sorry, my bad. I fixed my example to crop all pages and not just the first

**Comment by MTRNord** [comment]
Thanks this seems to solve my issue entirely :)

**Comment by TeXhackse** [comment]
I reopen it - not because it's not solved but because we'd love a different solution and @samcarter and me discussed that this might be a good enhancement. Though we'd prefer to have it in pgfpages directly instead of in handoutwithnotes.
